name: Aplicação Django

on: [pull_request]

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Instalar Dependências
        run: |
          pip install pipenv
          sync pipenv --dev
      - name: Rodar testes automaticos
        run: |
          pipenv run pytest webdev
          sync pipenv --dev